name: Update Medium Posts

on:
  # Disabled automatic triggers for now. To re-enable weekly runs on Mondays at 06:00 UTC, uncomment:
  # schedule:
  #   - cron: '0 6 * * 1'
  # Optional: re-add push triggers if desired
  # push:
  #   branches:
  #     - main
  #     - dev
  #   paths:
  #     - 'assets/scripts/fetch-medium.js'
  #     - 'blog/manifest.json'
  workflow_dispatch:
    # Manual triggering only (workflow effectively disabled from auto-runs)

# Allow this workflow to push changes back to the repository
permissions:
  contents: write

jobs:
  update-medium-posts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create blog images directory
        run: mkdir -p assets/images/blog
        
      - name: Fetch Medium posts and update manifest
        run: |
          export MEDIUM_RSS_URL="${MEDIUM_RSS_URL:-$DEFAULT_MEDIUM_RSS_URL}"
          node assets/scripts/fetch-medium.js
        env:
          DEFAULT_MEDIUM_RSS_URL: https://medium.com/feed/@markus.koefler11
          
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name != 'pull_request'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add blog/manifest.json
          git add assets/images/blog/
          git commit -m "Auto-update Medium posts and sync blog images"
          # Determine the target branch (handles schedule/workflow_dispatch with detached HEAD)
          BRANCH="${{ github.ref_name }}"
          if [ -z "$BRANCH" ] || [ "$BRANCH" = "HEAD" ]; then
            BRANCH="${DEFAULT_BRANCH:-main}"
          fi
          # Rebase on top of latest remote to avoid non-fast-forward errors
          git fetch origin "$BRANCH"
          git pull --rebase origin "$BRANCH"
          # Push to the current branch explicitly
          git push origin HEAD:"$BRANCH"
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}