name: Update Medium posts

on:
  schedule:
    - cron: '17 4 * * *'  # daily at 04:17 UTC
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-medium:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci || npm i
      - name: Fetch Medium RSS and update manifest
        run: node scripts/fetch-medium.js
      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain blog/manifest.json images/blog) ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add blog/manifest.json images/blog || true
            git commit -m "chore(blog): sync Medium posts and thumbnails"
            git push
          else
            echo "No changes to commit"
          fi
